### ISSUE TITLE
Is it edge case?

### ISSUE THREAD

**Issue by black7375** [NICHOLAS85/z-a-eval#1]
I've used your plugin and I'm satisfied.
There is a possibility that I used it incorrectly, but I found the wrong case.

**prev setting:**
```shell
_tldr-setting() {
  tldr --update
  local comp="$(tldr 2>/dev/null --list)"
  echo "complete -W \"$comp\" tldr" > init.zsh
}

zinit ice wait"2" as"command" from"gh-r" lucid \
      mv"tldr* -> tldr" atclone"_tldr-setting" pick"init.zsh" \
      atpull"%atclone" atload"alias man=tldr"
zinit light dbrgn/tealdeer
```

`init.zsh` result: so long..
https://gist.github.com/black7375/48cc53f92b29c94629c6930d2b95c381
```shell
complete -W "2to3
7z
7za
7zr
R
...
zramctl
zsh
zstd
zsteg
zypper" 

> tldr

```

**z-a-eval setting:**
```shell
zinit ice wait"2" as"command" from"gh-r" lucid \
      mv"tldr* -> tldr" atclone"./tldr --update" atpull"%atclone" \
      eval"echo complete -W $(./tldr 2>/dev/null --list) tldr" atload"alias man=tldr"
zinit light dbrgn/tealdeer
```

`evalcache.zsh` result:
```shell
# echo\ complete\ -W\ \ tldr
# generated with z-a-eval annex
if (( ZINIT_Z_A_EVAL_SOURCED )) { return; }
typeset -i ZINIT_Z_A_EVAL_SOURCED=1
complete -W tldr
```

**Additional context**
https://github.com/zdharma/zinit/issues/487

Thank you again for your hard work.

**Comment by NICHOLAS85** [comment]
I believe it has to do with your double quote `"` usage. The eval ice contents are being expanded in your zshrc instead of when you want them to (after the plugin is downloaded). Try using single quotes `'`. You'll also want to include the correct quoting like in your original setting inside the eval ice. I think the following will work for you:
```zsh
zinit ice wait"2" as"command" from"gh-r" lucid \
      mv"tldr* -> tldr" atclone"./tldr --update" atpull"%atclone" \
      eval'echo "complete -W \"$(./tldr 2>/dev/null --list)\" tldr"' atload"alias man=tldr"
zinit light dbrgn/tealdeer
```

**Comment by NICHOLAS85** [comment]
I might look into a `evalcache.zsh` previewing function which confirms with you if the contents look correct before saving. Might help prevent some headache if something gets incorrectly expanded.

**Comment by black7375** [comment]
Nice. It works!!
