### ISSUE TITLE
Does this support local plugins?

### ISSUE THREAD

**Issue by twang817** [NICHOLAS85/z-a-eval#3]
```
❯ tree -L 1 gnubin zinit/plugins
gnubin
└── gnubin.sh
zinit/plugins
└── _local---gnubin -> ../../gnubin
```

```bash
$ cat gnubin.sh
GNUBIN=$(find -L /usr/local/opt -type d -name gnubin | paste -sd':' -)
GNUMAN=$(find -L /usr/local/opt -type d -name gnuman | paste -sd':' -)
[ ! -z "$GNUBIN" ] && echo "export PATH=\"$GNUBIN:\$PATH\""
[ ! -z "$GNUMAN" ] && echo "export MANPATH=\"$GNUMAN:\$PATH\""
```

```bash
$ cat .zshrc
# ...
zinit depth'3' light-mode for \
    NICHOLAS85/z-a-eval

zinit light eval'./gnubin.sh' _local/gnubin
# ...
```

Output:
```
Downloading eval./gnubin.sh/_local/gnubin…

Cloning into '/root/.dotfiles/zsh/zinit/plugins/eval.---gnubin.sh---_local---gnubin'...
remote: Not Found
fatal: repository 'https://github.com/eval./gnubin.sh/_local/gnubin/' not found

Clone failed (code: 128).
```

**Comment by ss-o** [comment]
I assume it should be loaded like this:

```zsh
zinit ice eval'./gnubin.sh init zsh'
zinit light _local/gnubin
```


Some references which might help:

- [NICHOLAS85 zinit setup](https://github.com/z-shell/playground/tree/main/NICHOLAS85)
   - [_local---config-files](https://github.com/z-shell/playground/tree/main/NICHOLAS85/.zinit/plugins/_local---config-files)
- [Zsh-Plugin-Standard](https://github.com/z-shell/zi/wiki/Zsh-Plugin-Standard)

**Comment by twang817** [comment]
Aha!  I never learned the regular syntax, always went straight for the for syntax.

After adjusting the plugin loaded, but I'm getting a new error:

```
$ cat gnubin.sh
[ -d /usr/local/opt ] && {
    GNUBIN=$(find -L /usr/local/opt -type d -name gnubin | paste -sd':' -)
    GNUMAN=$(find -L /usr/local/opt -type d -name gnuman | paste -sd':' -)
}
[ ! -z "$GNUBIN" ] && echo "export PATH=\"$GNUBIN:\$PATH\""
[ ! -z "$GNUMAN" ] && echo "export MANPATH=\"$GNUMAN:\$MANPATH\""
echo "GNUBIN_LOADED=1"
```

```
$ cat evalcache.zsh
# ./gnubin.sh\ init\ zsh
# generated with z-a-eval annex
(( ZINIT_Z_A_EVAL_SOURCED )) && return
typeset -i ZINIT_Z_A_EVAL_SOURCED=1
GNUBIN_LOADED=1
```
^ This is correct that it didn't find any gnubin dirs.  I am running it on a PC instead of my MBP.

```
zinit depth'3' light-mode for \
    NICHOLAS85/z-a-eval \
    ;

zinit ice eval'./gnubin.sh init zsh'
zinit light _local/gnubin
```

When opening a shell, I get:

```
:za-ev-atinit-handler:23: no such file or directory: /root/.dotfiles/zsh/zinit/plugins/_local---gnubin/._zinit/eval
465d056cbdac# echo $GNUBIN_LOADED
1
465d056cbdac#
```

**Comment by twang817** [comment]
Apparently, the error above only appears once.

**Comment by ss-o** [comment]
Seems like your code outputs a non-zero exit code. 

- The optional preceding `!` the flag means to store command output regardless of exit code. Otherwise `eval''` will avoid caching the output of code that returns a non-zero exit code. 

```zsh
zinit ice eval'!./gnubin.sh init zsh'
zinit light _local/gnubin
```

I am just guessing here :octocat:

**Comment by ss-o** [comment]
It might be not specifically related here, but here are a few tips:
1. Your local config files should follow [Zsh-Plugin-Standard](https://github.com/z-shell/zi/wiki/Zsh-Plugin-Standard), otherwise it might not be recognized by the plugin manager and its functions.
  1.1 File should be named accordingly e.g. `*.plugin.zsh` or `*.init.zsh` and look similar to [NICHOLAS85/.zinit/plugins/_local---config-files/config-files.plugin.zsh](https://github.com/z-shell/playground/blob/main/NICHOLAS85/.zinit/plugins/_local---config-files/config-files.plugin.zsh)
  1.2 Follow directory map e.g: [NICHOLAS85/.zinit/plugins/_local---config-files](https://github.com/z-shell/playground/tree/main/NICHOLAS85/.zinit/plugins/_local---config-files)

**Comment by twang817** [comment]
> Seems like your code outputs a non-zero exit code.
> 
> * The optional preceding `!` the flag means to store command output regardless of exit code. Otherwise `eval''` will avoid caching the output of code that returns a non-zero exit code.
> 
> ```shell
> zinit ice eval'!./gnubin.sh init zsh'
> zinit light _local/gnubin
> ```
> 
> I am just guessing here :octocat:

I noticed that and put a `true` at the end of the script. I've also tried running with '!'  

I've since resolved my problem by creating a repo for this "plugin" on GitHub. But, I still think there might be an incompatibility between z-a-eval and local plugins. 

I'm no expert in zsh, but to me I think it boils down to the fact that the atclone never happens because the plugin is already on disk. Or, if it does, it may follow a different code path that doesn't create the ._zinit directory. 

z-a-eval wants to write to the $dir/._zinit/eval file during its atinit handler:

https://github.com/NICHOLAS85/z-a-eval/blob/b415f03dbebbc6896f2d7089ada9f9fcd8fc5cc2/:za-ev-atinit-handler#L23

At first, I was puzzled why this path isn't referenced anywhere else in the repo. But, then I found that it is created by zinit itself:

https://github.com/zdharma-continuum/zinit/blob/9ee45d6804fdf4972a9e913a1ad86d77de124231/zinit.zsh#L1092

zinit itself is too far beyond my ability to comprehend, but it appears to me that this directory never gets created for _local plugins. 

In any case, I'm no longer blocked and have moved on. I just wanted to document the behavior just in case anyone finds value in the report. Otherwise, thanks for the help!

**Comment by ss-o** [comment]
Good point, I assume a simple function would sort the issue? 

```zsh
  if [[ ! -r "$cachefile" && $ZINIT[annex-multi-flag:pull-active] -eq 0 ]] {
      # If locally added - create directory for eval ice.
      if [[ ! -d "$dir/._zinit" ]] {
          command mkdir -p  "$dir/._zinit"
      }
      builtin print -r -- "${ICE[eval]}" >! $dir/._zinit/eval
      :za-ev-atclone-handler "$1" "$2" "$3" "$4" "$5" "$6"
  }
```

**Comment by ss-o** [comment]
Hey @twang817,

I had some time spent regards managing things locally.

The best approach I was able to find is to modify the `zinit create` command and it worked out better as expected. In addition, I added a new feature called `dosync` which contains 2 files - `sync.config` and `custom.config`. Long story short:

1. `zinit create` - added additional options on plugin creations.
2. `dosync` - synchronizes and symlinks files anywhere while reading simple `sync.config`. For convenience `sync.custom` is being read for complex tasks.`dosync` can be managed anytime from the command line.

It literally organizes my files from dotfiles between local, remote environments as defined.
I'll publish it in near future. If you still having issues, let me know if it is what you trying to achieve.

Regards,

**Comment by NICHOLAS85** [comment]
Just pushed an update that might fix your error. Let me know if you continue to run into issues. Doing some testing of my own it seems Zinit should create the ._zinit directory even for local plugins so I'm not sure what's going on in your case.

**Comment by twang817** [comment]
I took a look at the diff, and I think it will help a lot.  I'll try it out a bit later tonight.  I've gone from barely understanding the zinit codebase to having given it a pretty decent read, and I have a lot better understanding of how its internals work now.

Regarding local scripts, I've gotten quite far by setting up locals as snippets.  Since I tend to organize a lot of my local stuff into a bunch of independent files, I haven't yet run into the issue where snippets can only refer to a single file.  I know you (and others) are using the `svn` ice to work around some of that.

Here is an example of using snippets instead of a local plugin:

```zsh
_loaded() {
    [[ ${zsh_loaded_plugins[(ie)$1]} -le ${#zsh_loaded_plugins} ]] && return 0 || return 1
}

zinit wait for \
    momo-lab/zsh-abbrev-alias \
    ;

zinit wait'_loaded momo-lab/zsh-abbrev-alias' is-snippet link for \
    has'alks'       id-as'aliases-alks'       $DFZ/aliases/alks.zsh \
    has'aws'        id-as'aliases-aws'        $DFZ/aliases/aws.zsh \
    has'brew'       id-as'aliases-brew'       $DFZ/aliases/brew.zsh \
    has'docker'     id-as'aliases-docker'     $DFZ/aliases/docker.zsh \
    has'git'        id-as'aliases-git'        $DFZ/aliases/hub.zsh \
    has'hub'        id-as'aliases-hub'        $DFZ/aliases/git.zsh \
    has'nvim'       id-as'aliases-nvim'       $DFZ/aliases/nvim.zsh \
    has'python'     id-as'aliases-python'     $DFZ/aliases/python.zsh \
    has'terraform'  id-as'aliases-terraform'  $DFZ/aliases/terraform.zsh \
    has'terragrunt' id-as'aliases-terragrunt' $DFZ/aliases/terragrunt.zsh \
    has'exa'        id-as'aliases-exa'        $DFZ/aliases/exa.zsh \
    ;
```

I added a new `link` ice that's currently in PR over at zinit.

https://github.com/zdharma-continuum/zinit/pull/150

This uses symlinks instead of copying files for snippets.  I found that snippets are an order of magnitude faster than even local plugins.  Though, this benchmark was observed back when I thought z-a-default-ice worked with `light-mode` (it does [not](https://github.com/zdharma-continuum/zinit-annex-default-ice/issues/4)).

I've also found z-a-eval to be really useful for snippets.  I've written up some stuff on the zinit wiki (still in PR, but hosted in [gh-pages on my fork](https://twang817.github.io/zinit/wiki/vivid-explanation/) ) showing how to combine z-a-eval and local snippets to handle some LS_COLORS stuff.

But, alas, my gnubin is still using a remote plugin:

```
zinit for \
    if'_is_osx' \
    nocompile \
    eval'./gnubin.sh' \
        twang817/zsh-gnubin \
```

I think I could convert this to a snippet with great effect; but, I'll give local plugin a shot to see if your changes worked for me.
